import { expect, test } from 'vitest'
import { extractThoughtsAndMessage } from './chat'
import { text } from 'stream/consumers'

test('Test thoughts extraction with slash', () => {
  const thoughts = extractThoughtsAndMessage(`<think>Testing123</think>Testing12345`)


  expect(thoughts).toEqual({ thoughts: ["Testing123"], text: "Testing12345" })
})


test('Test thoughts extraction with data', () => {
  const thoughts = extractThoughtsAndMessage(`<think>Okay, the user just typed \"trest\" without any context. That's pretty vague—could be anything from a medical term to an acronym or even a typo. First thought: maybe it's a misspelling of something more common, like \"stress.\" But I shouldn't assume that. The user might be in a hurry or not sure how to phrase their question properly.Let me brainstorm possibilities... Trest could relate to finance (like Treasury bonds), law (Treaty), medicine (T-rest test?), or even slang/tech terms. Oh, and it's also an Italian word for \"trust\" but that seems unlikely here unless the user is specifically referencing something from Italy. Hmm, this feels like one of those cases where I need to cover multiple bases without overwhelming them with options. The safest approach is to list plausible interpretations briefly and ask for clarification—no point diving deep into Treasury bonds if they actually meant \"stress\" or \"tryst.\" User's probably looking for quick help but didn't specify, so keeping it simple yet comprehensive in the reply makes sense. I'll structure it with categories (finance, law, medicine etc.) to show I'm thinking systematically without making them feel like a riddle needs solving. Should also leave an open-ended prompt at the end—they might not realize how vague their query is or be able to articulate what they need right away.</think>Okay, \"trest\" could refer to several things depending on context:1.  **Trespass:** This is a legal term referring to entering or remaining in another person's property without permission or invitation.2.  **Treasury (Financial):** Often shortened from U.S. Treasury, related to government finance and bonds.3.  **Treaty (Legal/Political):** An agreement made between states or organizations, often formalized internationally but can also be national agreements.4.  **Rest:** It could potentially be a misspelling of \"rest\" or part of an acronym where one word starts with 'R' and another ends with 'st'.Could you provide more context? Knowing what field (law, finance, medicine?) or sentence it appears in would help determine the correct meaning.`)

  expect(thoughts).toEqual({
    thoughts: ["Okay, the user just typed \"trest\" without any context. That's pretty vague—could be anything from a medical term to an acronym or even a typo. First thought: maybe it's a misspelling of something more common, like \"stress.\" But I shouldn't assume that. The user might be in a hurry or not sure how to phrase their question properly.Let me brainstorm possibilities... Trest could relate to finance (like Treasury bonds), law (Treaty), medicine (T-rest test?), or even slang/tech terms. Oh, and it's also an Italian word for \"trust\" but that seems unlikely here unless the user is specifically referencing something from Italy. Hmm, this feels like one of those cases where I need to cover multiple bases without overwhelming them with options. The safest approach is to list plausible interpretations briefly and ask for clarification—no point diving deep into Treasury bonds if they actually meant \"stress\" or \"tryst.\" User's probably looking for quick help but didn't specify, so keeping it simple yet comprehensive in the reply makes sense. I'll structure it with categories (finance, law, medicine etc.) to show I'm thinking systematically without making them feel like a riddle needs solving. Should also leave an open-ended prompt at the end—they might not realize how vague their query is or be able to articulate what they need right away."],
    text: "Okay, \"trest\" could refer to several things depending on context:1.  **Trespass:** This is a legal term referring to entering or remaining in another person's property without permission or invitation.2.  **Treasury (Financial):** Often shortened from U.S. Treasury, related to government finance and bonds.3.  **Treaty (Legal/Political):** An agreement made between states or organizations, often formalized internationally but can also be national agreements.4.  **Rest:** It could potentially be a misspelling of \"rest\" or part of an acronym where one word starts with 'R' and another ends with 'st'.Could you provide more context? Knowing what field (law, finance, medicine?) or sentence it appears in would help determine the correct meaning."
  })
})
