on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: apt-update
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update

      - name: autoremove
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt autoremove

      - name: Install libarchive rpm on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libarchive-tools rpm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        timeout-minutes: 15

      - name: Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        timeout-minutes: 30
        with:
          github_token: ${{ secrets.github_token }}
          release: true
